In [1]:
!pip install --upgrade pip
!pip install torch-summary
!pip install arabert transformers pytorch_lightning

Requirement already satisfied: pip in /opt/conda/lib/python3.10/site-packages (23.1.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting torch-summary
  Downloading torch_summary-1.4.5-py3-none-any.whl (16 kB)
Installing collected packages: torch-summary
Successfully installed torch-summary-1.4.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting arabert
  Downloading arabert-1.0.1-py3-none-any.whl (179 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 6.6 MB/s eta 0:00:00
Requirement already satisfied: transformers in /opt/conda/lib/python3.10/site-packages (4.29.2)
Requirement already satisfied: pytorch_lightning in /opt/conda/lib/python3.10/site-packages (2.0.2)
Requirement already satisfied: PyArabic in /opt/conda/lib/python3.10/site-packages (from arabert) (0.6.15)
Collecting farasapy (from arabert)
  Downloading farasapy-0.0.14-py3-none-any.whl (11 kB)
Collecting emoji==1.4.2 (from arabert)
  Downloading emoji-1.4.2.tar.gz (184 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.0/185.0 kB 16.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from transformers) (3.12.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in /opt/conda/lib/python3.10/site-packages (from transformers) (0.14.1)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from transformers) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from transformers) (21.3)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers) (5.4.1)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers) (2023.5.5)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers) (2.28.2)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /opt/conda/lib/python3.10/site-packages (from transformers) (0.13.3)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers) (4.64.1)
Requirement already satisfied: torch>=1.11.0 in /opt/conda/lib/python3.10/site-packages (from pytorch_lightning) (2.0.0)
Requirement already satisfied: fsspec[http]>2021.06.0 in /opt/conda/lib/python3.10/site-packages (from pytorch_lightning) (2023.5.0)
Requirement already satisfied: torchmetrics>=0.7.0 in /opt/conda/lib/python3.10/site-packages (from pytorch_lightning) (0.11.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /opt/conda/lib/python3.10/site-packages (from pytorch_lightning) (4.5.0)
Requirement already satisfied: lightning-utilities>=0.7.0 in /opt/conda/lib/python3.10/site-packages (from pytorch_lightning) (0.8.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/conda/lib/python3.10/site-packages (from fsspec[http]>2021.06.0->pytorch_lightning) (3.8.4)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging>=20.0->transformers) (3.0.9)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch>=1.11.0->pytorch_lightning) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch>=1.11.0->pytorch_lightning) (3.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch>=1.11.0->pytorch_lightning) (3.1.2)
Requirement already satisfied: six>=1.14.0 in /opt/conda/lib/python3.10/site-packages (from PyArabic->arabert) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->transformers) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->transformers) (2023.5.7)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /opt/conda/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning) (1.9.1)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.10/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch_lightning) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch>=1.11.0->pytorch_lightning) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch>=1.11.0->pytorch_lightning) (1.3.0)
Building wheels for collected packages: emoji
  Building wheel for emoji (setup.py) ... done
  Created wheel for emoji: filename=emoji-1.4.2-py3-none-any.whl size=186468 sha256=4df3c0973332093ca6fb511f13123dcd2e56913d7ad773262567e8fb26821bc3
  Stored in directory: /root/.cache/pip/wheels/10/f0/fd/4813b1177405693e8da9cdea839f0fb64fde161380e058c827
Successfully built emoji
Installing collected packages: emoji, farasapy, arabert
  Attempting uninstall: emoji
    Found existing installation: emoji 2.2.0
    Uninstalling emoji-2.2.0:
      Successfully uninstalled emoji-2.2.0
Successfully installed arabert-1.0.1 emoji-1.4.2 farasapy-0.0.14
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [ ]:
# !pip install install-jdk

# !pip install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-2.0-cp38-cp38-linux_x86_64.whl

In [2]:
!git clone https://github.com/ARBML/rouge_score_ar
%cd rouge_score_ar
!pip install -r requirements.txt
!pip install -e .
%cd ..

Cloning into 'rouge_score_ar'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 40 (delta 10), reused 30 (delta 7), pack-reused 0
Receiving objects: 100% (40/40), 25.95 KiB | 5.19 MiB/s, done.
Resolving deltas: 100% (10/10), done.
/kaggle/working/rouge_score_ar
Requirement already satisfied: absl-py in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: nltk in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (3.2.4)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (1.23.5)
Requirement already satisfied: six>=1.14 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Obtaining file:///kaggle/working/rouge_score_ar
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /opt/conda/lib/python3.10/site-packages (from rouge-score-ar==0.1.2) (1.4.0)
Requirement already satisfied: nltk in /opt/conda/lib/python3.10/site-packages (from rouge-score-ar==0.1.2) (3.2.4)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from rouge-score-ar==0.1.2) (1.23.5)
Requirement already satisfied: six>=1.14.0 in /opt/conda/lib/python3.10/site-packages (from rouge-score-ar==0.1.2) (1.16.0)
Installing collected packages: rouge-score-ar
  Running setup.py develop for rouge-score-ar
Successfully installed rouge-score-ar-0.1.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/kaggle/working

In [ ]:
!ls

In [ ]:
!mkdir 'data'
!mkdir 'data/train'
!mkdir 'data/dev'

In [ ]:
# import jdk
# from jdk.enums import OperatingSystem, Architecture

# jdk.install('11', operating_system=OperatingSystem.LINUX)

# import os

# os.environ['JAVA_HOME'] = '/root/.jdk/jdk-11.0.19+7'
# os.environ['PATH'] = f"{os.environ.get('PATH')}:{os.environ.get('JAVA_HOME')}/bin"

In [ ]:
# !java -version

In [ ]:
# !rm -r lightning_logs/

In [ ]:
# import os
# os.environ.pop('PJRT_DEVICE', None)

In [ ]:
from arabert.aragpt2.grover.modeling_gpt2 import GPT2LMHeadModel
from transformers import GPT2TokenizerFast

In [ ]:
MODEL_NAME='aubmindlab/aragpt2-base'

GPT_tokenizer = GPT2TokenizerFast.from_pretrained(MODEL_NAME)
# m = GPT2LMHeadModel.from_pretrained(MODEL_NAME, add_cross_attention=True, bad_words_ids=GPT_tokenizer.pad_token_id, decoder_start_token_id=GPT_tokenizer.)

In [ ]:
GPT_tokenizer.add_special_tokens( {'unk\_token': '<UNK>', 'sep\_token': '<SEP>', 'pad\_token': '<PAD>', 'cls\_token': '<CLS>'})

In [ ]:
GPT_tokenizer('أحمد يلعب الكره كل مساء', padding='max_length', max_length=100,)

In [ ]:
%cd rougecross_attention_hidden_size_score_ar
from rouge_score import rouge_scorer
%cd ..
import torch
from torchsummary import summary

from transformers import AutoTokenizer, AutoModel, BertLMHeadModel
from arabert.preprocess import ArabertPreprocessor


import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
import pytorch_lightning as pl

from pytorch_lightning.callbacks import ModelCheckpoint, StochasticWeightAveraging
from pytorch_lightning.callbacks import  RichProgressBar
from pytorch_lightning.callbacks.progress.rich_progress import RichProgressBarTheme

import pandas as pd
import os
import copy
from tqdm import tqdm
import numpy as np
import pickle
import random

In [ ]:
def avg_rough(preds, target):
    metric = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'])
    scores = list(map(lambda x: metric.score(*x), zip(preds, target)))
    sum_rough = dict()
    max_len = len(scores)
    for item in scores:
        for key, score in item.items():
            if key not in sum_rough.keys():
                sum_rough[key] = dict()
                sum_rough[key]['fmeasure'] = score.fmeasure
                sum_rough[key]['recall'] = score.recall
                sum_rough[key]['precision'] = score.precision
            else:
                sum_rough[key]['fmeasure'] += score.fmeasure
                sum_rough[key]['recall'] += score.recall
                sum_rough[key]['precision'] += score.precision
            
    for key, score in sum_rough.items():
        for metric, value in score.items():
            sum_rough[key][metric] = sum_rough[key][metric] / max_len
            
        sum_rough[key] = sum_rough[key]['fmeasure']
    
    return sum_rough

In [ ]:
class Data(Dataset):
    def __init__(self, data, batch_size, in_size=512, out_size=100):
        self.data_values = data
        self.batch_size = batch_size
        self.in_size = in_size
        self.out_size = out_size

    def __getitem__(self, idx):
        path = self.data_values[idx]
        
        with open(path, 'rb') as f:
            batch = pickle.load(f)
            
        r = np.random.randint(0, 12, (self.batch_size,)).tolist()
        
        for k, v in batch.items():
            if k != 'label_out':
                for kk, vv in v.items():
                    vv.data = vv[r]
            else:
                v.data = v[r]
        
        return batch['seq_in'], (batch['label_in'], batch['label_out'])

    def __len__(self):
        return len(self.data_values)

In [ ]:
class EncoderDecoder4Summary(pl.LightningModule):
    def __init__(self, model_name, pad_token_id, max_position_embeddings, decoder=None, ckp=None, lr=1e-4):
        super().__init__()
        
        self.save_hyperparameters()
        
        self.encoder = AutoModel.from_pretrained(model_name, pad_token_id=self.hparams.pad_token_id, max_position_embeddings=max_position_embeddings, ignore_mismatched_sizes=True, position_embedding_type='relative')
        self.encoder.pooler = None
        self.decoder = BertLMHeadModel.from_pretrained(model_name, pad_token_id=self.hparams.pad_token_id, is_decoder=True, add_cross_attention=True, position_embedding_type='relative')
        self = self.cpu()
        
        if ckp is not None:
            with torch.no_grad():
                ckp = torch.load(ckp, map_location='cpu',)['state_dict']
                for n, p in self.encoder.named_parameters():
                    if p.size() != ckp[f'encoder.{n}'].size():
                        print('not intialize layer', n , 'from checkpoint')
                        continue
                    p.data = ckp[f'encoder.{n}'].cpu()
                for n, p in self.decoder.named_parameters():
                    if p.size() != ckp[f'decoder.{n}'].size():
                        print('not intialize layer', n , 'from checkpoint')
                        continue
                    p.data = ckp[f'decoder.{n}'].cpu()

            print('checkpoint loaded succfflly')
            
        self.train()
        for n, p in self.encoder.named_parameters():
            if False:
                p.requires_grad_(True)
            else:
                p.requires_grad_(False)
                
        for n, p in self.decoder.named_parameters():
    
#             if 'position' in n or 'word_embeddings' in n:
#                 p.requires_grad_(False)
#             else:
            p.requires_grad_(True)
                
    def forward(self, seq, label):

        context = self.encoder(**seq).last_hidden_state
        out = self.decoder(**label, encoder_hidden_states=context, encoder_attention_mask=seq['attention_mask'])
        return out

    def training_step(self, batch, batch_idx):
        seq, (label_in, label_out) = batch
        out = self(seq, label_in)
        loss = F.cross_entropy(out.logits.transpose(2, 1), label_out, ignore_index=self.encoder.config.pad_token_id)

        self.log('Loss', loss, on_step=True, on_epoch=False, sync_dist=True, prog_bar=True,)
        return loss

    def validation_step(self, batch, batch_idx):
        seq, (label_in, label_out) = batch

        out = self(seq, label_in)

        loss = F.cross_entropy(out.logits.transpose(2, 1), label_out, ignore_index=self.encoder.config.pad_token_id)
        preds  = torch.argmax(out.logits, -1)
        preds  = bert_tokenizer.batch_decode(preds, skip_special_tokens=True)
        preds = list(map(bert_prep.unpreprocess, preds))
        
        target = bert_tokenizer.batch_decode(label_out, skip_special_tokens=True)
        target = list(map(bert_prep.unpreprocess, target))
        rough = avg_rough(preds, target)
        rough['val_loss'] = loss
        self.log_dict(rough, on_epoch=True, sync_dist=True, prog_bar=True)


    def configure_optimizers(self):
        pp = [p for p in self.parameters() if p.requires_grad]
        opt = torch.optim.AdamW(pp, lr=self.hparams.lr, weight_decay=0.1)
        return opt
        scheduler = {
            "scheduler": CosineAnnealingWarmRestarts(optimizer, T_0=6, T_mult=2, eta_min=0, verbose=True),
            "interval": "epoch",
            "frequency": 1,}
        return [optimizer], [scheduler]

In [ ]:
ckp = ModelCheckpoint(every_n_train_steps=100, save_last=True, auto_insert_metric_name=False)
progress_bar=RichProgressBar(theme=RichProgressBarTheme(description="green_yellow",
                                                          progress_bar="green1",
                                                          progress_bar_finished="green1",
                                                          progress_bar_pulse="#6206E0",
                                                          batch_progress="green_yellow",
                                                          time="grey82",
                                                          processing_speed="grey82",
                                                          metrics="green1"))

In [ ]:
model_name = "aubmindlab/bert-base-arabertv2"
ckp_path = '/kaggle/input/salah-checkpoint/lightning_logs/version_0/checkpoints/last.ckpt' #change to None for fresh model

bert_prep = ArabertPreprocessor(model_name=model_name)
bert_tokenizer = AutoTokenizer.from_pretrained(model_name,)

model = EncoderDecoder4Summary(model_name, bert_tokenizer.pad_token_id, 1000, ckp=ckp_path, lr=1e-5)
summary(model)

import gc
gc.collect()
torch.cuda.empty_cache()

In [ ]:
pl.seed_everything(43, True)
dev_path   = '/kaggle/input/cocked-data/dev'
test_path  = '/kaggle/input/cocked-data/test'
train_path = '/kaggle/input/cocked-data/train'
labeld_valid = '/kaggle/input/cocked-data/labeld_valid'

In [ ]:
train = list(map(lambda x: os.path.join(train_path, x), os.listdir(train_path)))
labeld_valid = list(map(lambda x: os.path.join(labeld_valid, x), os.listdir(labeld_valid)))
train = labeld_valid + labeld_valid + labeld_valid  + labeld_valid + labeld_valid + train[:-9] + labeld_valid + labeld_valid  + labeld_valid + labeld_valid
random.shuffle(train)
train = np.array(train)
dev = np.array(list(map(lambda x: os.path.join(dev_path, x), os.listdir(dev_path))))
test = np.array(list(map(lambda x: os.path.join(test_path, x), os.listdir(test_path))))

labeld_valid = np.array(labeld_valid)

In [ ]:
batch_size = 4

train = Data(train, batch_size, 1000, 300)
train = DataLoader(train, batch_size=None, shuffle=True, num_workers=2)

dev = Data(dev, batch_size, 1000, 300)
dev = DataLoader(dev, batch_size=None, shuffle=False, num_workers=2)

test = Data(test, batch_size, 1000, 300)
test = DataLoader(test, batch_size=None, shuffle=False, num_workers=2)

labeld_valid = Data(labeld_valid, batch_size, 1000, 300)
labeld_valid = DataLoader(labeld_valid, batch_size=None, shuffle=False, num_workers=2)

In [ ]:
gc.collect()
torch.cuda.empty_cache()
trainer = pl.Trainer(accelerator='auto', devices='auto',
                     max_epochs=200,
#                      max_time='00:11:00:00',
                     strategy='auto',
                     num_sanity_val_steps=2,
#                      limit_train_batches=10,

                     log_every_n_steps=25,
                     callbacks=[ckp, progress_bar],
                     accumulate_grad_batches=1, #precision='16-mixed',
                     gradient_clip_val=0.5,
                     sync_batchnorm=True,
                     logger=True,
                     enable_model_summary=True, enable_checkpointing=True, #benchmark=True,
                     default_root_dir=os.getcwd())


trainer.fit(model, labeld_valid, labeld_valid) #, ckpt_path='lightning_logs/version_0/checkpoints/epoch=5-step=504.ckpt')

In [ ]:
# !rm -r lightning_logs/

In [ ]:
new_ckp = 'lightning_logs/version_0/checkpoints/last.ckpt'
new_model = EncoderDecoder4Summary(model_name, bert_tokenizer.pad_token_id, 1000, ckp=new_ckp, lr=1e-4)

In [ ]:
def generate(document, model, pre, tok, max_lenght=511):
    model.eval().cuda()
    pre_doc = pre.preprocess(document)
    pre_doc = tok(pre_doc, return_attention_mask=True, padding='max_length', max_length=1000, truncation=True, return_tensors='pt')
    seq_in  = dict()
    seq_in['input_ids']  = pre_doc.input_ids.cuda()
    seq_in['attention_mask'] = pre_doc.attention_mask.cuda()
    seq_in['token_type_ids'] = pre_doc.token_type_ids.cuda()
    
    output_ids = torch.ones((1, 1)).long().cuda() * tok.cls_token_id
    with torch.no_grad():
        context  = model.encoder(**seq_in).last_hidden_state
        for i in range(max_lenght):
            next_ids = model.decoder(output_ids, encoder_hidden_states=context, encoder_attention_mask=seq_in['attention_mask'], output_attentions=False)
            next_ = torch.multinomial(next_ids.logits[0, -1, :].softmax(-1), 1)
            next_ = torch.unsqueeze(next_, 0)
            output_ids = torch.concat([output_ids, next_], 1)

            if tok.sep_token_id == next_[0, 0]:
                break
                
    output = tok.batch_decode(output_ids.cpu(), skip_special_tokens=True)[0]
    output = pre.unpreprocess(output)
    return output#, next_ids.cross_attentions

In [ ]:
new_test = pd.read_csv('/kaggle/input/arabic-text-summarization/data/labeld_valid.csv').values

In [ ]:
result = {'example_id':[], 'summary':[], 'truth': []}

for i in tqdm(range(len(new_test))):
    title, doc, summ = new_test[i]
    
    pre = generate(doc, new_model, bert_prep, bert_tokenizer)
    
    result['example_id'].append(i)
    result['summary'].append(pre)
    result['truth'].append(summ)

In [ ]:
avg_rough(result['summary'], result['truth'])

In [ ]:
result['summary'][4]

In [ ]:
result['truth'][4]

In [4]:
# !pip install git+https://github.com/ARBML/rouge_score_ar
!pip install accelerate -U

Requirement already satisfied: accelerate in /opt/conda/lib/python3.10/site-packages (0.12.0)
Collecting accelerate
  Downloading accelerate-0.20.3-py3-none-any.whl (227 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.6/227.6 kB 8.5 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from accelerate) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from accelerate) (21.3)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from accelerate) (5.9.3)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.10/site-packages (from accelerate) (5.4.1)
Requirement already satisfied: torch>=1.6.0 in /opt/conda/lib/python3.10/site-packages (from accelerate) (2.0.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging>=20.0->accelerate) (3.0.9)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch>=1.6.0->accelerate) (3.12.0)
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.10/site-packages (from torch>=1.6.0->accelerate) (4.5.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch>=1.6.0->accelerate) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch>=1.6.0->accelerate) (3.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch>=1.6.0->accelerate) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch>=1.6.0->accelerate) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch>=1.6.0->accelerate) (1.3.0)
Installing collected packages: accelerate
  Attempting uninstall: accelerate
    Found existing installation: accelerate 0.12.0
    Uninstalling accelerate-0.12.0:
      Successfully uninstalled accelerate-0.12.0
Successfully installed accelerate-0.20.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [7]:
import pandas as pd
import tensorflow as tf
from rouge_score import rouge_scorer

In [ ]:
validation = pd.read_csv('/kaggle/input/t5-ar-finetune/data/dev/labeld_valid.csv')

In [1]:
from transformers import pipeline
from transformers import TFMT5ForConditionalGeneration, MT5Tokenizer

/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tensorflow13GcsFileSystemE']
  warnings.warn(f"file system plugins are not loaded: {e}")

In [2]:
model_name = '/kaggle/input/t5-ar-finetune/sebay/t5_ar'

# summarizer = pipeline("summarization", model=model_name, tokenizer=model_name, framework="tf")

tokenizer = MT5Tokenizer.from_pretrained(model_name)
        
model = TFMT5ForConditionalGeneration.from_pretrained(model_name)

/opt/conda/lib/python3.10/site-packages/keras/initializers/initializers.py:120: UserWarning: The initializer RandomNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(
All model checkpoint layers were used when initializing TFMT5ForConditionalGeneration.

All the layers of TFMT5ForConditionalGeneration were initialized from the model checkpoint at /kaggle/input/t5-ar-finetune/sebay/t5_ar.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFMT5ForConditionalGeneration for predictions without further training.

In [3]:
model.save_pretrained("sebay/t5_ar_torch", safetensors=True) 
tokenizer.save_pretrained("sebay/t5_ar_torch")

('sebay/t5_ar_torch/tokenizer_config.json',
 'sebay/t5_ar_torch/special_tokens_map.json',
 'sebay/t5_ar_torch/spiece.model',
 'sebay/t5_ar_torch/added_tokens.json')

In [4]:
del model, tokenizer

In [5]:
import gc
gc.collect()

70

In [2]:
import torch
from transformers import MT5ForConditionalGeneration, MT5Tokenizer
from accelerate import init_empty_weights, infer_auto_device_map

/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tensorflow13GcsFileSystemE']
  warnings.warn(f"file system plugins are not loaded: {e}")

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [29]:
!rm -r sebay/t5_ar_torch

In [1]:
!ls sebay/t5_ar_torch

config.json		pytorch_model.bin	 spiece.model
generation_config.json	special_tokens_map.json  tokenizer_config.json

In [4]:
import torch
from transformers import MT5ForConditionalGeneration, MT5Tokenizer
from accelerate import init_empty_weights, infer_auto_device_map

model_name = 'sebay/t5_ar_torch'
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# summarizer = pipeline("summarization", model=model_name, tokenizer=model_name, framework="tf")

tokenizer = MT5Tokenizer.from_pretrained(model_name)

model = MT5ForConditionalGeneration.from_pretrained(model_name, from_tf=True) #,
model.save_pretrained("sebay/t5_ar_torch",) 
tokenizer.save_pretrained("sebay/t5_ar_torch") 

# model = MT5ForConditionalGeneration.from_pretrained(model_name, torch_dtype=torch.float16)
# model.to(device);

In [5]:
model.device

device(type='cpu')

In [5]:
# model.to(device);

In [1]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline
from arabert.preprocess import ArabertPreprocessor

model_name="abdalrahmanshahrour/arabartsummarization"
preprocessor = ArabertPreprocessor(model_name="")

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
pipeline = pipeline("text2text-generation",model=model,tokenizer=tokenizer)

text = "شهدت مدينة طرابلس، مساء أمس الأربعاء، احتجاجات شعبية وأعمال شغب لليوم الثالث على التوالي، وذلك بسبب تردي الوضع المعيشي والاقتصادي. واندلعت مواجهات عنيفة وعمليات كر وفر ما بين الجيش اللبناني والمحتجين استمرت لساعات، إثر محاولة فتح الطرقات المقطوعة، ما أدى إلى إصابة العشرات من الطرفين."
text = preprocessor.preprocess(text)

result = pipeline(text,
            pad_token_id=tokenizer.eos_token_id,
            num_beams=3,
            repetition_penalty=3.0,
            max_length=200,
            length_penalty=1.0,
            no_repeat_ngram_size = 3)[0]['generated_text']

print(result)

/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tensorflow13GcsFileSystemE']
  warnings.warn(f"file system plugins are not loaded: {e}")

Downloading (…)okenizer_config.json:   0%|          | 0.00/502 [00:00<?, ?B/s]

Downloading (…)tencepiece.bpe.model:   0%|          | 0.00/1.32M [00:00<?, ?B/s]

Downloading (…)/main/tokenizer.json:   0%|          | 0.00/3.78M [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/279 [00:00<?, ?B/s]

Downloading (…)lve/main/config.json:   0%|          | 0.00/1.48k [00:00<?, ?B/s]

Downloading pytorch_model.bin:   0%|          | 0.00/557M [00:00<?, ?B/s]

تجددت الاشتباكات بين الجيش اللبناني ومحتجين في مدينة طرابلس شمالي لبنان.

In [6]:
# @tf.function
def generate_summary_pt(text):
    input_ids = tokenizer(
                        [text],
                        return_tensors="pt",
#                         padding="max_length",
                        truncation=True,
                        max_length=2000
                        )["input_ids"].to(device)

    output_ids = model.generate(
                                input_ids=input_ids,
                                max_new_tokens=900,
                                min_new_tokens= int(0.075 * len(text)),
                                no_repeat_ngram_size=4,
                                num_beams=25,
                                renormalize_logits =True,
                                temperature = 0.3,
                                top_k=100,
                                top_p = 0.7,
                                length_penalty=0.3,
                                )[0]
    summary = tokenizer.decode(
                                output_ids.cpu(),
                                skip_special_tokens=True,
                                clean_up_tokenization_spaces=True
                                )
    return summary

In [2]:
import pandas as pd
from tqdm import tqdm
validation = pd.read_csv('/kaggle/input/arabic-text-summarization/data/labeld_valid.csv')

In [15]:
validation = pd.read_csv('/kaggle/input/arabic-text-summarization/data/unlabeld_valid.csv')

In [16]:
validation

     example_id                                           document
0             0  وبعد أن ألقينا الضوء على أهم فتوحات بلاد الشام...
1             1  الفتوحات الإسلامية في عصر الخلفاء الراشدين .\n...
2             2  فتوحات بلاد شمال إفريقيا .\nقام المسلمون بالتو...
3             3  وبعد أن ألقينا الضوء على أهم فتوحات بلاد شمال ...
4             4  عزيزي الطالب / عزيزتي الطالبة ...\nبعد أن توقف...
..          ...                                                ...
267         267  وظهرت كثير من الدراسات قصرت اهتمامها على الأدو...
268         268  كانت الزراعة المصرية في هذه الحقبة تمر بعصرها ...
269         269  حشدت فرنسا قواتها وأعلنت الحرب في 19 يوليو أي ...
270         270  تعتبر قناة السويس هي من أهم الطرق الملاحية الت...
271         271  فالثورة الفرنسية ، وهي محل شاهد في صراع الطبقا...

[272 rows x 2 columns]

In [14]:
!rm rouge_score_ar/

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
rm: cannot remove 'rouge_score_ar/': Is a directory

In [19]:
result = {'example_id':[], 'summary': []}

for row in tqdm(validation.values):
    result['example_id'].append(row[0])
#     generated_summary = generate_summary_pt(row[1])
    generated_summary = preprocessor.preprocess(row[1])

    generated_summary = pipeline(generated_summary,
                pad_token_id=tokenizer.eos_token_id,
                num_beams=3,
                min_new_tokens=int(0.065 * len(generated_summary)),
                repetition_penalty=3.0,
                max_length=200,
                length_penalty=1.0,
                no_repeat_ngram_size = 3)[0]['generated_text']
    result['summary'].append(generated_summary)

100%|██████████| 272/272 [26:49<00:00,  5.92s/it]

In [20]:
final_submission = pd.DataFrame.from_records(result)

In [21]:
final_submission.to_json('predictions.jsonl', lines=True, orient='records', force_ascii=False)

In [23]:
final_submission.summary[10]

'بعد عشرة أيام من معركة بلاط الشهداء ( تور - بواتييه ) 114 ه - 732 م ، تمكن جيش المسلمين بقيادة " عبد الرحمن الغافقي " من فتح النصف الجنوبي لفرنسا، وترك حاميات عسكرية في المدن التي فتحها مما أضعف قوة جيشه قبيل لقائه مع " شارل مارتل " الذي استنجد به طالبا العون منه لاسترجاع دوقية أكوتين المسيحية من فرنسا. فما هي الأسباب التي أدت إلى هزيمة المسلمين في هذه المعركة ؟'

In [4]:
import pandas as pd
from tqdm import tqdm
validation = pd.read_csv('/kaggle/input/arabic-text-summarization/data/labeld_valid.csv')

In [5]:
validation

,example_id,document,summary
0,0,وتحت عنوان من الكارثة إلى التحدى يبدأ الكاتب ع...,يبدأ الكاتب عرض الكتاب الرابع تحت عنوان من الك...
1,1,ولم يعترف دبلوماسيو هاتين الدولتين بالعريضة ال...,دبلوماسيو الدولتين لم يعترفوا بالعريضة التي قا...
2,2,قامت ولاية حلب بعد اعلان الجنرال الفرنسي هنري ...,أعلن غورو الانتداب الفرنسي على سوريا لكي يعاقب...
3,3,دولة مصر العربيه هي ليست اي دوله وليست اي شعب ...,مصر هي أم البلاد، وقائدة العرب؛ فهي أرض بلاد ا...
4,4,السوريون يصرون على استقلال بلادهم : و مثلما رف...,الشعب السوري يصر على استقلال بلدهم من السيطرة ...
...,...,...,...
149,149,حزب الوفد سيحتفل بمئوية ثورة 1919 يوم 9 مارس ا...,احتفال مئوية ثورة 1919 كان من منطلق وطني ليس ح...
150,150,حيث أعلن مجلس قيادة الثورة في 18 يونيه 1953 قي...,مجلس قيادة الثورة أعلن عن قيام الجمهورية المصر...
151,151,وبرغم أن عبد الرحمن فهمي كان يضم في ذلك الجهاز...,ضم عبد الرحمن فهمي في الجهاز السري عدد كبير من...
152,152,ولم تقتصر مقومات بورسعيد كمدينة عالمية منذ نشأ...,امتدت بورسعيد لكي تشمل الطابع الثقافي للمدينة،...
153,153,أول رئيس للجزائر بعد الاستقلال الرئيس أحمد بن ...,كان أحمد بن بيلا أول رئيس للجزائر بعد الاستقلا...

In [62]:
# @tf.function
def generate_summary_pt(text):
    input_ids = tokenizer(
                        [text],
                        return_tensors="pt",
                        truncation=True,
                        max_length=2000
                        )["input_ids"].to(device)

    output_ids = model.generate(
                                input_ids=input_ids,
                                max_new_tokens=int(3*0.08 * len(text)),
                                penalty_alpha=0.6,
                                min_new_tokens= int(0.06 * len(text)),
                                no_repeat_ngram_size=4,
                                num_beams=25,
                                renormalize_logits =True,
                                temperature = 0.6,
#                                 top_k=3,
                                top_p = 0.9,
                                length_penalty=0.3,
                                )[0]
    summary = tokenizer.decode(
                                output_ids.cpu(),
                                skip_special_tokens=True,
                                clean_up_tokenization_spaces=True
                                )
    return summary

In [12]:
scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"])
scores = []
ll = len(validation.values)
for i, article in enumerate(validation.values):
    
    generated_summary = preprocessor.preprocess(article[1])
    rat = int(0.075 * len(article[1]))
    print("\r processing {} from {} with min token length {} and doc length {}".format(i, len(validation), rat, len(article[1].split())), end = "")
#     with tf.device('CPU'):
    generated_summary = pipeline(generated_summary,
                pad_token_id=tokenizer.eos_token_id,
                num_beams=3,
                min_new_tokens= int(0.075 * len(generated_summary)),
                repetition_penalty=3.0,
                max_length=200,
                length_penalty=1.0,
                no_repeat_ngram_size = 3)[0]['generated_text']
    new_score = scorer.score(article[2], generated_summary)
    scores.append(new_score)

    print("\tWith ROUGE scores: " , end= "")
    
    ss = {"rouge1": new_score["rouge1"].fmeasure ,
        "rouge2": new_score["rouge2"].fmeasure,
        "rougeL": new_score["rougeL"].fmeasure}
                   
   
    print(ss)
    
#     print('Ground Truth:')
#     print('\t\t', article[2])
#     print()
#     print('Model Prediction')
#     print('\t\t', generated_summary)
#     print()
#     print('='*20)

print()
print('='*50)
avg = {"rouge1": (sum(s["rouge1"].fmeasure for s in scores ) / ll),
        "rouge2": (sum(s["rouge2"].fmeasure for s in scores) / ll),
        "rougeL": (sum(s["rougeL"].fmeasure for s in scores) / ll)}
print('Average ROUGE scores', avg)

 processing 0 from 154 with min token length 134 and doc length 335	With ROUGE scores: {'rouge1': 0.2882882882882883, 'rouge2': 0.08181818181818182, 'rougeL': 0.16216216216216217}
 processing 1 from 154 with min token length 116 and doc length 277	With ROUGE scores: {'rouge1': 0.24203821656050953, 'rouge2': 0.09032258064516129, 'rougeL': 0.11464968152866241}
 processing 2 from 154 with min token length 143 and doc length 339	With ROUGE scores: {'rouge1': 0.24875621890547264, 'rouge2': 0.05025125628140704, 'rougeL': 0.1791044776119403}
 processing 3 from 154 with min token length 119 and doc length 282	With ROUGE scores: {'rouge1': 0.18584070796460175, 'rouge2': 0.0625, 'rougeL': 0.09734513274336283}
 processing 4 from 154 with min token length 107 and doc length 259	With ROUGE scores: {'rouge1': 0.21333333333333332, 'rouge2': 0.05405405405405405, 'rougeL': 0.1333333333333333}
 processing 5 from 154 with min token length 154 and doc length 368	With ROUGE scores: {'rouge1': 0.20883534136546186, 'rouge2': 0.048582995951417005, 'rougeL': 0.13654618473895583}
 processing 6 from 154 with min token length 151 and doc length 355	With ROUGE scores: {'rouge1': 0.16580310880829016, 'rouge2': 0.041884816753926704, 'rougeL': 0.11398963730569948}
 processing 7 from 154 with min token length 105 and doc length 262	With ROUGE scores: {'rouge1': 0.24358974358974358, 'rouge2': 0.1038961038961039, 'rougeL': 0.17948717948717946}
 processing 8 from 154 with min token length 158 and doc length 374	With ROUGE scores: {'rouge1': 0.3851851851851852, 'rouge2': 0.16417910447761194, 'rougeL': 0.17777777777777778}
 processing 9 from 154 with min token length 147 and doc length 337	With ROUGE scores: {'rouge1': 0.17391304347826086, 'rouge2': 0.039024390243902446, 'rougeL': 0.09661835748792272}
 processing 10 from 154 with min token length 129 and doc length 309	With ROUGE scores: {'rouge1': 0.2702702702702703, 'rouge2': 0.08743169398907102, 'rougeL': 0.16216216216216214}
 processing 11 from 154 with min token length 152 and doc length 351	With ROUGE scores: {'rouge1': 0.30901287553648066, 'rouge2': 0.0606060606060606, 'rougeL': 0.16309012875536483}
 processing 12 from 154 with min token length 137 and doc length 313	With ROUGE scores: {'rouge1': 0.21978021978021978, 'rouge2': 0.11111111111111112, 'rougeL': 0.1978021978021978}
 processing 13 from 154 with min token length 126 and doc length 277	With ROUGE scores: {'rouge1': 0.2622950819672131, 'rouge2': 0.08839779005524862, 'rougeL': 0.15300546448087435}
 processing 14 from 154 with min token length 130 and doc length 315	With ROUGE scores: {'rouge1': 0.4666666666666666, 'rouge2': 0.32584269662921345, 'rougeL': 0.28888888888888886}
 processing 15 from 154 with min token length 134 and doc length 302	With ROUGE scores: {'rouge1': 0.3016759776536313, 'rouge2': 0.13559322033898308, 'rougeL': 0.2346368715083799}
 processing 16 from 154 with min token length 166 and doc length 369	With ROUGE scores: {'rouge1': 0.15966386554621848, 'rouge2': 0.0, 'rougeL': 0.050420168067226885}
 processing 17 from 154 with min token length 148 and doc length 349	With ROUGE scores: {'rouge1': 0.17435897435897432, 'rouge2': 0.05181347150259067, 'rougeL': 0.11282051282051282}
 processing 18 from 154 with min token length 151 and doc length 369	With ROUGE scores: {'rouge1': 0.29357798165137616, 'rouge2': 0.11111111111111112, 'rougeL': 0.13761467889908258}
 processing 19 from 154 with min token length 143 and doc length 351	With ROUGE scores: {'rouge1': 0.22123893805309736, 'rouge2': 0.08035714285714285, 'rougeL': 0.1415929203539823}
 processing 20 from 154 with min token length 120 and doc length 300	With ROUGE scores: {'rouge1': 0.19672131147540983, 'rouge2': 0.03314917127071823, 'rougeL': 0.08743169398907105}
 processing 21 from 154 with min token length 143 and doc length 350	With ROUGE scores: {'rouge1': 0.12307692307692307, 'rouge2': 0.0, 'rougeL': 0.061538461538461535}
 processing 22 from 154 with min token length 129 and doc length 323	With ROUGE scores: {'rouge1': 0.25837320574162675, 'rouge2': 0.10628019323671498, 'rougeL': 0.16267942583732056}
 processing 23 from 154 with min token length 118 and doc length 293	With ROUGE scores: {'rouge1': 0.2037037037037037, 'rouge2': 0.056074766355140186, 'rougeL': 0.10185185185185185}
 processing 24 from 154 with min token length 165 and doc length 372	With ROUGE scores: {'rouge1': 0.26778242677824265, 'rouge2': 0.09282700421940929, 'rougeL': 0.16736401673640167}
 processing 25 from 154 with min token length 96 and doc length 252	With ROUGE scores: {'rouge1': 0.15492957746478875, 'rouge2': 0.014285714285714285, 'rougeL': 0.08450704225352111}
 processing 26 from 154 with min token length 163 and doc length 383	With ROUGE scores: {'rouge1': 0.1888412017167382, 'rouge2': 0.06926406926406925, 'rougeL': 0.12875536480686697}
 processing 27 from 154 with min token length 136 and doc length 336	With ROUGE scores: {'rouge1': 0.3008849557522124, 'rouge2': 0.0625, 'rougeL': 0.10619469026548671}
 processing 28 from 154 with min token length 155 and doc length 380	With ROUGE scores: {'rouge1': 0.26341463414634153, 'rouge2': 0.1083743842364532, 'rougeL': 0.14634146341463417}
 processing 29 from 154 with min token length 114 and doc length 303	With ROUGE scores: {'rouge1': 0.17333333333333337, 'rouge2': 0.013513513513513513, 'rougeL': 0.10666666666666666}
 processing 30 from 154 with min token length 161 and doc length 386	With ROUGE scores: {'rouge1': 0.27027027027027023, 'rouge2': 0.07272727272727272, 'rougeL': 0.14414414414414414}
 processing 31 from 154 with min token length 135 and doc length 329	With ROUGE scores: {'rouge1': 0.3508771929824561, 'rouge2': 0.18584070796460178, 'rougeL': 0.1929824561403509}
 processing 32 from 154 with min token length 161 and doc length 375

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /tmp/ipykernel_200/1284468113.py:10 in <module>                                                  │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/tmp/ipykernel_200/1284468113.py'                          │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/pipelines/text2text_generation.py:165 in    │
│ __call__                                                                                         │
│                                                                                                  │
│   162 │   │   │     ids of the generated text.                                                   │
│   163 │   │   """                                                                                │
│   164 │   │                                                                                      │
│ ❱ 165 │   │   result = super().__call__(*args, **kwargs)                                         │
│   166 │   │   if (                                                                               │
│   167 │   │   │   isinstance(args[0], list)                                                      │
│   168 │   │   │   and all(isinstance(el, str) for el in args[0])                                 │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1119 in __call__          │
│                                                                                                  │
│   1116 │   │   │   │   )                                                                         │
│   1117 │   │   │   )                                                                             │
│   1118 │   │   else:                                                                             │
│ ❱ 1119 │   │   │   return self.run_single(inputs, preprocess_params, forward_params, postproces  │
│   1120 │                                                                                         │
│   1121 │   def run_multi(self, inputs, preprocess_params, forward_params, postprocess_params):   │
│   1122 │   │   return [self.run_single(item, preprocess_params, forward_params, postprocess_par  │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1126 in run_single        │
│                                                                                                  │
│   1123 │                                                                                         │
│   1124 │   def run_single(self, inputs, preprocess_params, forward_params, postprocess_params):  │
│   1125 │   │   model_inputs = self.preprocess(inputs, **preprocess_params)                       │
│ ❱ 1126 │   │   model_outputs = self.forward(model_inputs, **forward_params)                      │
│   1127 │   │   outputs = self.postprocess(model_outputs, **postprocess_params)                   │
│   1128 │   │   return outputs                                                                    │
│   1129                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py:1025 in forward           │
│                                                                                                  │
│   1022 │   │   │   │   inference_context = self.get_inference_context()                          │
│   1023 │   │   │   │   with inference_context():                                                 │
│   1024 │   │   │   │   │   model_inputs = self._ensure_tensor_on_device(model_inputs, device=se  │
│ ❱ 1025 │   │   │   │   │   model_outputs = self._forward(model_inputs, **forward_params)         │
│   1026 │   │   │   │   │   model_outputs = self._ensure_tensor_on_device(model_outputs, device=  │
│   1027 │   │   │   else:                                                                         │
│   1028 │   │   │   │   raise ValueError(f"Framework {self.framework} is not supported")          │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/pipelines/text2text_generation.py:187 in    │
│ _forward                                                                                         │
│                                                                                                  │
│   184 │   │   generate_kwargs["min_length"] = generate_kwargs.get("min_length", self.model.con   │
│   185 │   │   generate_kwargs["max_length"] = generate_kwargs.get("max_length", self.model.con   │
│   186 │   │   self.check_inputs(input_length, generate_kwargs["min_length"], generate_kwargs["   │
│ ❱ 187 │   │   output_ids = self.model.generate(**model_inputs, **generate_kwargs)                │
│   188 │   │   out_b = output_ids.shape[0]                                                        │
│   189 │   │   if self.framework == "pt":                                                         │
│   190 │   │   │   output_ids = output_ids.reshape(in_b, out_b // in_b, *output_ids.shape[1:])    │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py:115 in decorate_context       │
│                                                                                                  │
│   112 │   @functools.wraps(func)                                                                 │
│   113 │   def decorate_context(*args, **kwargs):                                                 │
│   114 │   │   with ctx_factory():                                                                │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
│   116 │                                                                                          │
│   117 │   return decorate_context                                                                │
│   118                                                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py:1604 in generate        │
│                                                                                                  │
│   1601 │   │   │   │   **model_kwargs,                                                           │
│   1602 │   │   │   )                                                                             │
│   1603 │   │   │   # 13. run beam search                                                         │
│ ❱ 1604 │   │   │   return self.beam_search(                                                      │
│   1605 │   │   │   │   input_ids,                                                                │
│   1606 │   │   │   │   beam_scorer,                                                              │
│   1607 │   │   │   │   logits_processor=logits_processor,                                        │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py:2902 in beam_search     │
│                                                                                                  │
│   2899 │   │   │                                                                                 │
│   2900 │   │   │   model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)  │
│   2901 │   │   │                                                                                 │
│ ❱ 2902 │   │   │   outputs = self(                                                               │
│   2903 │   │   │   │   **model_inputs,                                                           │
│   2904 │   │   │   │   return_dict=True,                                                         │
│   2905 │   │   │   │   output_attentions=output_attentions,                                      │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl            │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/models/mbart/modeling_mbart.py:1358 in      │
│ forward                                                                                          │
│                                                                                                  │
│   1355 │   │   │   if decoder_input_ids is None and decoder_inputs_embeds is None:               │
│   1356 │   │   │   │   decoder_input_ids = shift_tokens_right(labels, self.config.pad_token_id)  │
│   1357 │   │                                                                                     │
│ ❱ 1358 │   │   outputs = self.model(                                                             │
│   1359 │   │   │   input_ids,                                                                    │
│   1360 │   │   │   attention_mask=attention_mask,                                                │
│   1361 │   │   │   decoder_input_ids=decoder_input_ids,                                          │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl            │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/models/mbart/modeling_mbart.py:1238 in      │
│ forward                                                                                          │
│                                                                                                  │
│   1235 │   │   │   )                                                                             │
│   1236 │   │                                                                                     │
│   1237 │   │   # decoder outputs consists of (dec_features, past_key_value, dec_hidden, dec_att  │
│ ❱ 1238 │   │   decoder_outputs = self.decoder(                                                   │
│   1239 │   │   │   input_ids=decoder_input_ids,                                                  │
│   1240 │   │   │   attention_mask=decoder_attention_mask,                                        │
│   1241 │   │   │   encoder_hidden_states=encoder_outputs[0],                                     │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl            │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/models/mbart/modeling_mbart.py:1103 in      │
│ forward                                                                                          │
│                                                                                                  │
│   1100 │   │   │   │   │   None,                                                                 │
│   1101 │   │   │   │   )                                                                         │
│   1102 │   │   │   else:                                                                         │
│ ❱ 1103 │   │   │   │   layer_outputs = decoder_layer(                                            │
│   1104 │   │   │   │   │   hidden_states,                                                        │
│   1105 │   │   │   │   │   attention_mask=attention_mask,                                        │
│   1106 │   │   │   │   │   encoder_hidden_states=encoder_hidden_states,                          │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl            │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/models/mbart/modeling_mbart.py:444 in       │
│ forward                                                                                          │
│                                                                                                  │
│    441 │   │   │                                                                                 │
│    442 │   │   │   # cross_attn cached key/values tuple is at positions 3,4 of present_key_valu  │
│    443 │   │   │   cross_attn_past_key_value = past_key_value[-2:] if past_key_value is not Non  │
│ ❱  444 │   │   │   hidden_states, cross_attn_weights, cross_attn_present_key_value = self.encod  │
│    445 │   │   │   │   hidden_states=hidden_states,                                              │
│    446 │   │   │   │   key_value_states=encoder_hidden_states,                                   │
│    447 │   │   │   │   attention_mask=encoder_attention_mask,                                    │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl            │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/models/mbart/modeling_mbart.py:190 in       │
│ forward                                                                                          │
│                                                                                                  │
│    187 │   │   bsz, tgt_len, _ = hidden_states.size()                                            │
│    188 │   │                                                                                     │
│    189 │   │   # get query proj                                                                  │
│ ❱  190 │   │   query_states = self.q_proj(hidden_states) * self.scaling                          │
│    191 │   │   # get key, value proj                                                             │
│    192 │   │   # `past_key_value[0].shape[2] == key_value_states.shape[1]`                       │
│    193 │   │   # is checking that the `sequence_length` of the `past_key_value` is the same as   │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl            │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │

In [ ]:
avg = {"rouge1": (sum(s["rouge1"].fmeasure for s in scores ) / 154),
        "rouge2": (sum(s["rouge2"].fmeasure for s in scores) / 154),
        "rougeL": (sum(s["rougeL"].fmeasure for s in scores) / 154)}
print('Average ROUGE scores', avg)

In [ ]:
 sum(s["rouge1"].fmeasure for s in scores )/154